config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home_guest'
  resources :foods
end

app/models/food.rb
class Food < ActiveRecord::Base
	# Associations
	has_many :food_quantities
	has_many :quantities
  has_many :nut_vals
	has_many :food_nut_vals

	# Validations
	validates :name, presence: true
	validates :calories, presence: true
end

app/models/food_nut_val.rb
class FoodNutVal < ActiveRecord::Base
	# Associations
	belongs_to :food
  belongs_to :nut_val

	# Validations
	validates :food_id, presence: true
	validates :nut_val_id, presence: true
end

app/models/food_quantity.rb
class FoodQuantity < ActiveRecord::Base
	# Associations
	belongs_to :food
	belongs_to :quantity

	# Validations
	validates :food_id, presence: true
	validates :quantity_id, presence: true
end

app/models/nut_val.rb
class NutVal < ActiveRecord::Base
	# Associations
	has_many :foods
	has_many :food_nut_vals

	# Validations
	validates :name, presence: true
	validates :value, presence: true
	validates :unit , presence: true
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
	# Associations
	has_many :foods
	has_many :food_quantities

	# Validations
	validates :serving_size, presence: true
	validates :value, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
	def index
		@foods = Food.all
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home_guest
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<h1>Foods Index Page</h1>

<p>
	<%= link_to "Home", root_path %>
</p>

<% @foods.each do |food| %>
	<p>
		Name: <%= food.name %>
		<br>
		Calories: <%= food.calories %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>REPLACE WITH YOUR APP NAME</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <!--
    Turbolinks can be used to improve the page load times but can also result
    in hard-to-debug problems with JavaScript. If you want this, uncomment
    it and remove line 6.
    -->
    <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home_guest.html.erb
<h1>Hello World</h1>



<%= link_to "Foods", foods_path %>